# Generated by Django 3.2 on 2021-05-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MouseBlogs', '0003_remove_blogpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogpost',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
